name: Frontend Check. If changes detected, Deploy new image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The deployment environment to use"
      topic_name:
        required: true
        type: string
        description: "The base name of the project"
      deployment_date:
        required: true
        type: string
        description: "Deployment date identifier (e.g., 052225)"
      deployment_color:
        required: true
        type: string
        description: "Deployment color (e.g., blue, blue, green)"
      cms_dir_name:
        required: true
        type: string
        description: "Directory containing CMS code"
      cms_container_name:
        required: true
        type: string
        description: "Name for the CMS container"
      cms_image_name:
        required: true
        type: string
        description: "Docker image name for the CMS"
    secrets:
      LINUX_SSH_PRIVATE_KEY_CICD:
        required: true
      LINUX_BOTCICDGHA_USERNAME:
        required: true
      LINUX_SERVER_IPADDRESS:
        required: true
      GHPAT_AS_CICD_SECRET:
        required: true
      PAYLOAD__SECRET_ENV_FILE:
        required: true
    outputs:
      had_changes:
        description: "Whether changes were detected"
        value: ${{ jobs.job-deploy--cms-fe.outputs.changes_detected }}
      action_taken:
        description: "Action taken during deployment"
        value: ${{ jobs.job-deploy--cms-fe.outputs.action }}
      changed_files:
        description: "List of files that were changed"
        value: ${{ jobs.job-deploy--cms-fe.outputs.changed_files }}
      changed_files_count:
        description: "Number of files that were changed"
        value: ${{ jobs.job-deploy--cms-fe.outputs.changed_files_count }}
jobs:
  job-deploy--cms-fe:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write # Needed for artifact operations
    outputs:
      changes_detected: ${{ steps.check-changes.outputs.changes }}
      action: ${{ steps.step-deploy--cms-fe.outputs.action_taken || steps.no-deployment.outputs.action_taken }}
      changed_files: ${{ steps.changed-files.outputs.files }}
      changed_files_count: ${{ steps.changed-files.outputs.count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history needed for better change detection

      # Setup GitHub CLI for artifact operations
      - name: Setup GitHub CLI
        run: |
          echo "Setting up GitHub CLI authentication..."
          echo ${{ github.token }} | gh auth login --with-token

      # Download last successful deployment marker if it exists
      - name: Download last successful deployment marker
        id: download-marker
        continue-on-error: true # Continue if no marker exists yet
        run: |
          mkdir -p ./deployment-markers

          # Try to download the artifact using the GitHub CLI
          echo "Attempting to download latest cms-fe-last-deployed-commit artifact..."
          gh run download --name cms-fe-last-deployed-commit --dir ./deployment-markers --repo ${{ github.repository }} || true

          # Check if the download was successful
          if [ -f "./deployment-markers/last-cms-fe-commit.txt" ]; then
            echo "✅ Successfully downloaded previous deployment marker"
          else
            echo "⚠️ No previous deployment marker found or download failed"
          fi

      # Check if the CMS container exists on the server
      - name: Check if CMS Container exists on server
        id: check-container-exists
        env:
          SSH_KEY: ${{ secrets.LINUX_SSH_PRIVATE_KEY_CICD }}
          SSH_USER: ${{ secrets.LINUX_BOTCICDGHA_USERNAME }}
          SERVER_IP: ${{ secrets.LINUX_SERVER_IPADDRESS }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SERVER_IP
            User $SSH_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          END

          # Check if CMS container exists (running or stopped)
          CONTAINER_EXISTS=$(ssh prod "docker ps -a --format '{{.Names}}' | grep -q '^${{ inputs.cms_container_name }}$' && echo 'true' || echo 'false'")

          echo "container_exists=$CONTAINER_EXISTS" >> $GITHUB_OUTPUT
          echo "Container exists: $CONTAINER_EXISTS"

      # Determine last deployed commit hash
      - name: Get last deployed commit hash
        id: get-last-commit
        run: |
          if [ -f "./deployment-markers/last-cms-fe-commit.txt" ]; then
            LAST_COMMIT=$(cat ./deployment-markers/last-cms-fe-commit.txt)
            echo "Last successfully deployed frontend commit: $LAST_COMMIT"
            echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT
          else
            # If no marker exists, get a commit far back enough to capture all changes
            # This will trigger a build on first run
            LAST_COMMIT=$(git rev-list --max-parents=0 HEAD)
            echo "No previous deployment marker found. Using initial commit: $LAST_COMMIT"
            echo "last_commit=$LAST_COMMIT" >> $GITHUB_OUTPUT
          fi

      - name: Check PayloadCMS Directory Changes
        id: check-changes
        run: |
          echo "=== Running checks ==="

          # STEP 1: Show container status from previous check
          CONTAINER_EXISTS="${{ steps.check-container-exists.outputs.container_exists }}"
          echo "* Container exists: $CONTAINER_EXISTS"

          # STEP 2: Show commit comparison with abbreviated hashes
          CURRENT_COMMIT=$(git rev-parse HEAD)
          CURRENT_COMMIT_SHORT=$(git rev-parse --short HEAD)
          LAST_COMMIT="${{ steps.get-last-commit.outputs.last_commit }}"
          LAST_COMMIT_SHORT=$(git rev-parse --short $LAST_COMMIT)

          echo "* Comparing current commit $CURRENT_COMMIT_SHORT with last deployed $LAST_COMMIT_SHORT"

          # STEP 3: Check for actual code changes in the CMS directory
          CHANGES=$(git diff --name-only $LAST_COMMIT HEAD -- ./${{ inputs.cms_dir_name }})

          # STEP 4: Determine deployment action based on two factors:
          # Factor A: Are there code changes?
          # Factor B: Does the container exist?

          if [ -z "$CHANGES" ]; then
            # NO CODE CHANGES detected
            echo "* Changes detected in payloadcms-cms directory since last deployment? NO"
            
            if [ "$CONTAINER_EXISTS" = "false" ]; then
              # DEPLOYMENT LOGIC: No code changes BUT container missing
              # ACTION: Build current commit version and deploy (container needs to exist)
              echo "* Container doesn't exist - forcing deployment despite no code changes"
              echo "* DECISION: Will build current commit version and deploy"
              echo "changes=true" >> $GITHUB_OUTPUT
              echo "force_deploy_reason=Container does not exist" >> $GITHUB_OUTPUT
            else
              # DEPLOYMENT LOGIC: No code changes AND container exists
              # ACTION: No deployment needed
              echo "* Container exists and no code changes detected"
              echo "* DECISION: No deployment needed"
              echo "changes=false" >> $GITHUB_OUTPUT
              echo "no changes detected" > ./cms-fe-changed-files.txt
            fi
          else
            # CODE CHANGES detected
            echo "* Changes detected in payloadcms-cms directory since last deployment? YES"
            echo "* DECISION: Will build current commit version and deploy"
            echo "changes=true" >> $GITHUB_OUTPUT
            
            # Save changed files list for deployment summary
            echo "$CHANGES" > ./cms-fe-changed-files.txt
          fi

      # Save changed files to an output instead of using artifacts
      - name: Set changed files as output
        if: steps.check-changes.outputs.changes == 'true'
        id: changed-files
        run: |
          # Use GitHub's multiline output syntax
          echo "files<<EOF" >> $GITHUB_OUTPUT
          cat ./cms-fe-changed-files.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Count the number of changed files correctly
          CHANGE_COUNT=$(cat ./cms-fe-changed-files.txt | wc -l | xargs)
          echo "count=$CHANGE_COUNT" >> $GITHUB_OUTPUT

      - name: Install YQ
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load Environment Defaults
        id: env-defaults
        run: |
          # Extract PayloadCMS environment variables from defaults file
          PAYLOADCMS_DEFAULTS=$(yq e '.payloadcms_defaults' .github/defaults/env-defaults.yml)
          echo "$PAYLOADCMS_DEFAULTS" > ./${{ inputs.cms_dir_name }}/env-defaults.env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHPAT_AS_CICD_SECRET }}

      - name: Ensure entrypoint script is executable
        id: verify-entrypoint
        if: steps.check-changes.outputs.changes == 'true'
        run: chmod +x ./${{ inputs.cms_dir_name }}/entrypoint.sh

      - name: Build Image with Default Secrets, then Publish
        id: build-publish
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          echo "Building and publishing frontend Docker image..."

          # Build the PayloadCMS Docker image with env file
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg ENV_FILE=env-defaults.env \
            --build-arg SKIP_NEXTJS_BUILD=true \
            --no-cache \
            -t ${{ inputs.cms_image_name }} \
            ./${{ inputs.cms_dir_name }}
            
          # Push the Docker image to GitHub Container Registry
          docker push ${{ inputs.cms_image_name }}

          #  Delete local env var file (defaults) after transfer
          rm ./${{ inputs.cms_dir_name }}/env-defaults.env

          echo "BUILT=true" >> $GITHUB_ENV
          echo "PUSHED=true" >> $GITHUB_ENV
          echo "build_status=success" >> $GITHUB_OUTPUT

      - name: Create production migrations directory on server if it doesn't exist
        if: steps.check-changes.outputs.changes == 'true'
        env:
          SSH_KEY: ${{ secrets.LINUX_SSH_PRIVATE_KEY_CICD }}
          SSH_USER: ${{ secrets.LINUX_BOTCICDGHA_USERNAME }}
          SERVER_IP: ${{ secrets.LINUX_SERVER_IPADDRESS }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SERVER_IP
            User $SSH_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          END

          # Create migrations directory ON THE HOST SERVER if it doesn't exist
          # Note: This is necessary for bind mounts because:
          # 1. It ensures the host directory exists before container startup
          # 2. It sets proper ownership of the directory as the SSH user
          # 3. While Docker can create it automatically, this gives us control over permissions
          # 4. The entrypoint.sh also creates this directory inside the container as a backup
          # the bind mounts will be located at: 
          # /home/<githubCICDUsername>/payloadcms-052225blue-cms__migrations
          # /home/<githubCICDUsername>/payloadcms-052225blue-cms__media
          ssh prod "mkdir -p ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms__migrations"

          # We'll also need a media directory to be persisted as a bind mount
          ssh prod "mkdir -p ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms__media"

      - name: SSH in and Deploy Updated CMS-Frontend image with Prod Secrets
        id: step-deploy--cms-fe
        if: steps.check-changes.outputs.changes == 'true'
        env:
          SSH_KEY: ${{ secrets.LINUX_SSH_PRIVATE_KEY_CICD }}
          SSH_USER: ${{ secrets.LINUX_BOTCICDGHA_USERNAME }}
          SERVER_IP: ${{ secrets.LINUX_SERVER_IPADDRESS }}
          GHPAT: ${{ secrets.GHPAT_AS_CICD_SECRET }}
          PAYLOADCMS__PROD_ENV: ${{ secrets.PAYLOAD__SECRET_ENV_FILE }}
        run: |
          # Setup SSH - simplified approach
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Create SSH config using heredoc for consistency
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SERVER_IP
            User $SSH_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          END
                
          # Verify connection to server with simple commands
          echo "Verifying server connection..."
          ssh prod "hostname && which docker && uptime"

          # First authenticate with GHCR on the remote server
          echo "Authenticating with GitHub Container Registry on remote server..."
          ssh prod "echo '$GHPAT' | docker login ghcr.io -u ${{ github.actor }} --password-stdin"

          # Create a temporary env file on the remote server
          echo "Creating temporary environment file..."
          ssh prod "echo '$PAYLOADCMS__PROD_ENV' > ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms-env.env"

          # Ensure Docker network exists (create if it doesn't)
          ssh prod "docker network ls --filter name=private-${{ inputs.topic_name }}-${{ inputs.deployment_color }}-dockernet -q | grep -q . || docker network create private-${{ inputs.topic_name }}-${{ inputs.deployment_color }}-dockernet"

          # Deploy to remote server with environment file
          # The critical addition here is the bind mount for migration & media directories
          ssh prod "docker pull ${{ inputs.cms_image_name }} && \
                    docker rm -f ${{ inputs.cms_container_name }} || true && \
                    docker run -d \
                      --name ${{ inputs.cms_container_name }} \
                      --network private-${{ inputs.topic_name }}-${{ inputs.deployment_color }}-dockernet \
                      --network main-network--npm020325 \
                      -p 3000:3000 \
                      --env-file ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms-env.env \
                      -v ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms__migrations:/app/src/migrations \
                      -v ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms__media:/app/public/media \
                      ${{ inputs.cms_image_name }}"

          echo "Deleting temporarily created prod env file..."
          ssh prod "rm ~/${{ inputs.topic_name }}-${{ inputs.deployment_date }}${{ inputs.deployment_color }}-cms-env.env"

          # Deployment successful - set appropriate action message
          if [ -n "${{ steps.check-changes.outputs.force_deploy_reason }}" ]; then
            # This was a forced deployment due to missing container
            echo "action_taken=Deployed: ${{ steps.check-changes.outputs.force_deploy_reason }}" >> $GITHUB_OUTPUT
          else
            # This was a normal deployment due to code changes  
            echo "action_taken=New version deployed" >> $GITHUB_OUTPUT
          fi
          echo "deploy_status=success" >> $GITHUB_ENV

      # Set no deployment action for when no deployment is needed
      - name: Set no deployment action
        if: steps.check-changes.outputs.changes == 'false'
        id: no-deployment
        run: |
          # No deployment was needed - container exists and no code changes
          echo "action_taken=No deployment needed - container exists and no code changes" >> $GITHUB_OUTPUT

      # Save deployment marker if deploy was successful
      - name: Save deployment marker
        if: steps.check-changes.outputs.changes == 'true' && env.deploy_status == 'success'
        run: |
          mkdir -p ./deployment-markers
          git rev-parse HEAD > ./deployment-markers/last-cms-fe-commit.txt
          echo "Saved current commit as last deployed commit marker"

      # Upload the marker as an artifact
      - name: Upload deployment marker
        if: steps.check-changes.outputs.changes == 'true' && env.deploy_status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: cms-fe-last-deployed-commit
          path: ./deployment-markers/last-cms-fe-commit.txt
          retention-days: 90

      - name: Status Report
        run: |
          echo "Frontend Deployment Status:"
          echo "Changes Detected: ${{ steps.check-changes.outputs.changes }}"
          echo "Action Taken: ${{ steps.step-deploy--cms-fe.outputs.action_taken || steps.no-deployment.outputs.action_taken }}"
